#!/bin/python3

# This is script is intent to convert monkeytype language json files to a simple words.txt with single word per line

import sys
import json

if len(sys.argv) < 3:
    print("You need to specify the input and output paths!")
    exit()

input = sys.argv[1]
output = sys.argv[2]

with open(output, "w") as words:
    with open(input, "r") as jsonFile:
        data = json.load(jsonFile)

        print("Converting '%s' dataset..." % (data["name"]))

        max_len = 0
        for word in data["words"]:
            words.write(word + "\n")
            max_len = max(max_len, len(word))

        print("Word count: %d\nMax word length: %d" % (len(data["words"]), max_len))
