#!/bin/bash

MONKYPE_DIR="$HOME/.local/share/monkype"
DATASETS_DIR="$MONKYPE_DIR/datasets"

RAW_LINK="https://raw.githubusercontent.com/monkeytypegame/monkeytype/refs/heads/master/frontend/static/languages"

dataset_name="$1"
if [ -z "$dataset_name" ]; then
  echo "usage monkype-get <dataset>"
  echo
  echo -e "Install and use datasets from original \e[34mMonkey Type's github\e[0m"
  echo

  if [ -n "$(ls $DATASETS_DIR)" ]; then
    echo "Installed datasets:"
    for i in $(ls $DATASETS_DIR); do
      echo -e "  \e[32m*\e[0m ${i:0:-4}"
    done
  else
    echo "No installed datasets"
  fi

  echo
  echo -e "NOTE: Use \e[34m'monkype-list <query>'\e[0m to list downloadable datasets"

  exit 1
fi

# Ensure datasets dir exists
mkdir -p $DATASETS_DIR

dataset_file="$DATASETS_DIR/$dataset_name.txt"

if [ ! -f "$dataset_file" ]; then
  echo "Downloading..."

  tmp_file="$MONKYPE_DIR/tmp"
  rm "$tmp_file" >/dev/null 2>&1
  
  wget "$RAW_LINK/${dataset_name}.json" -O "$tmp_file" >/dev/null 2>&1
  status=$?

  if [ $status -eq 0 ]; then
    monkype-convert "$tmp_file" "$dataset_file"
  else
    echo "  * Can't download dataset '${dataset_name}'."
  fi
  
  rm "$tmp_file" >/dev/null 2>&1
fi

cp "$dataset_file" "$MONKYPE_DIR/words.txt" >/dev/null 2>&1
status=$?

if [ $status -eq 0 ]; then
  echo "$dataset_name" > "$MONKYPE_DIR/.dataset"
  echo -e "Using dataset \e[34m$dataset_name\e[0m"
else
  echo "Couldn't get dataset."
  exit 1
fi
